### PR TITLE
Site Editor: Fix error in compileStyleValue

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Regression after #43019.

RR fixes `uncompiledValue.startsWith is not a function` error in `compileStyleValue`.

## Why?
Based on theme config the `uncompiledValue` can be an integer, and this causes an error.

## How?
Updated condition to check the uncompiledValue type.

## Testing Instructions
I noticed the error when visiting the site editor using [Stewart](https://wordpress.org/themes/stewart/) theme.

1. Using the Stewart theme visit the Site Editor.
2. Confirm there're no JS errors.

## Screenshots or screencast 

CleanShot 2022-08-10 at 14 17 25

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 1]
```diff
@@ -49,7 +49,11 @@ function compileStyleValue( uncompiledValue ) {
 	const VARIABLE_REFERENCE_PREFIX = 'var:';
 	const VARIABLE_PATH_SEPARATOR_TOKEN_ATTRIBUTE = '|';
 	const VARIABLE_PATH_SEPARATOR_TOKEN_STYLE = '--';
-	if ( uncompiledValue?.startsWith( VARIABLE_REFERENCE_PREFIX ) ) {
+
+	if (
+		typeof uncompiledValue === 'string' &&
+		uncompiledValue.startsWith( VARIABLE_REFERENCE_PREFIX )
+	) {
```
Comment (tyxla) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]: Shorter alternative:

```suggestion
	if ( uncompiledValue?.startsWith?.( VARIABLE_REFERENCE_PREFIX ) ) {
```

**Review by tyxla — APPROVED** [review]
Thanks for the fix. I've suggested a shorter alternative for your consideration.

**Comment by Mamaduka** [comment]
Thanks for the quick review, @tyxla. Shorter alternative works for me 👍

**Comment by Mamaduka** [comment]
Hi, @oandregal. It might be a good idea to cherry-pick this for 13.9.

**Comment by priethor** [comment]
Cherry-picked to the 13.9 branch and released in Gutenberg 13.9-rc2 ✅
