### ISSUE TITLE
Customizer: Error in console after opening a widget area when a theme opts-out of the new block-based “Widgets” screen

### ISSUE THREAD

**Issue by pagelab** [WordPress/gutenberg#24949]
**Describe the bug**
Since Gutenberg 8.9.0 RC1 (#24087) it is possible to opt-out of the new block-based “Widgets” screen adding `remove_theme_support( 'widgets-block-editor' );` to any theme.

This keeps the legacy “Widgets” screen and prevent the new block-based “Widgets” screen to appear. 

But doing so does not bring back the legacy “Widgets” section on the customizer.

It's crucial to maintain this section for backward compatibility reasons, specially for themes that heavily use widgets for layout purposes or widgets that have many visual controls, like color pickers.

**To reproduce**
1. Using any theme, add `remove_theme_support( 'widgets-block-editor' );` in the `functions.php` file to opt-out of the new block-based “Widgets” screen.
2. Install and activate the Gutenberg 8.9.0 RC1 plugin in “Plugins → Add new”.
3. Click “Appearance → Customize”.
4. See that the legacy “Widgets” section is missing.

**Expected behavior**
When a theme opts-out of the new block-based “Widgets” screen, the legacy “Widgets” section should appear on the customizer.

**Screenshots**
![missing-widgets-section-customizer](https://user-images.githubusercontent.com/1451087/91773078-71921700-ebbc-11ea-8a38-86faa59eae47.gif)

**Editor version:**
- WordPress version: 5.5.0
- Gutenberg [8.9.0 RC1](https://github.com/WordPress/gutenberg/releases/tag/v8.9.0-rc.1)
- TwentyTwenty 1.5

**Desktop:**
 - macOS 10.14.6
 - Chrome 85

**Comment by adamziel** [comment]
This is temporarily fixed by merging https://github.com/WordPress/gutenberg/pull/25626, although the discussion about the fate of the customizer editor is still ongoing: https://github.com/WordPress/gutenberg/issues/25625. I'm marking it as blocked for now.

**Comment by bph** [comment]
I tested this with master today. 
The Widget section appears in the Customizer and I could add and delete widgets without any problems.

**Comment by pagelab** [comment]
I did a test with Gutenberg version 9.2.2 and the issue persists. But it's working on WordPress 5.6-beta1-49308.

**Comment by draganescu** [comment]
I am reopening this as trying to test with the Gutenberg plugin activated, adding `remove_theme_support( 'widgets-block-editor' );` will result in `Uncaught Error: Call to undefined method stdClass::_register() in wp-includes/class-wp-widget-factory.php:102`.

**Comment by noisysocks** [comment]
@draganescu: Where are you seeing that error? When I enable the Gutenberg plugin, enable the Widgets screen in Customizer experiment, add `remove_theme_support( 'widgets-block-editor' );` to `gutenberg.php`, and browse to Appearance → Customize → Widgets I see the old interface and no error.

**Comment by draganescu** [comment]
That  was a while ago @noisysocks 
Tested again, now there is no more PHP error, however, with the block widgets disabled from the theme functions file, I get the widgets panel back but currently on `trunk` opening that section or adding an image widget results in `Uncaught TypeError: t.onChangeSectionExpanded is not a function`

**Comment by tellthemachines** [comment]
I can partially reproduce this by adding `remove_theme_support( 'widgets-block-editor' );` to my theme's `functions.php`. I can access the Widgets section in the Customizer but attempting to open any of the widgets for editing causes `Uncaught TypeError: control.onChangeSectionExpanded is not a function` to appear in the browser console.

**Comment by kevin940726** [comment]
`remove_theme_support( 'widgets-block-editor' )` doesn't seem to work at all now. I opened [trac-53424](https://core.trac.wordpress.org/ticket/53424#ticket) to track it.

**Comment by getdave** [comment]
Looks like this was fixed in https://github.com/WordPress/wordpress-develop/pull/1382.

More details in Trac.

https://core.trac.wordpress.org/ticket/53424#ticket

Can we close this one out now @noisysocks?
