### ISSUE TITLE
New installations of @wordpress/env installs docker-compose 0.24.4 and throws an error on usage

### ISSUE THREAD

**Issue by angcl** [WordPress/gutenberg#59183]
### Description

When installing the @wordpress/env package, it installs the new version of the [docker-compose|https://www.npmjs.com/package/docker-compose] dependency (0.24.4), which results in an error that says `dockerCompose.down is not a function`. It works flawlessly with the version 0.24.3.

### Step-by-step reproduction instructions

* Create a new folder
* Initialize npm `npm init -y`
* Install wp-env `npm install @wordpress/env --save-dev`
* Run `npx wp-env start`

### Screenshots, screen recording, code snippet

```
❯ mkdir new-project
❯ cd new-project
❯ npm init -y
❯ npm install @wordpress/env --save-dev
❯ npx wp-env start
✖ dockerCompose.down is not a function
TypeError: dockerCompose.down is not a function
    at stop (/Users/.../node_modules/@wordpress/env/lib/commands/stop.js:27:22)
    at async start (/Users/.../node_modules/@wordpress/env/lib/commands/start.js:111:3)
```

### Environment info

macOS 14.2.1
Node.js v18.19.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by angcl** [comment]
For me, it worked to use the prior version 0.24.3 of docker-compose in the package.json.

```
    "devDependencies": {
        ...
        "@wordpress/env": "^9.3.0",
        "docker-compose": "0.24.3",
        ...
    },
```

**Comment by peperuda** [comment]
The problem is that in the destroy.js and in the stop.js the function `compose.down` is used, but this function was renamed with docker-compose v0.24.4 to `compose.downAll` .

**Comment by angcl** [comment]
Should work with the new version (0.24.6) of docker-compose out-of-the-box.
https://github.com/PDMLab/docker-compose/pull/264

**Comment by youknowriad** [comment]
Closing as not reproducible on current versions: fresh wp-env installs and starts run cleanly today (verified repeatedly with the same ^0.24.x dependency line this reported against — the upstream package fixed its regression). If a clean install still throws for anyone, please share the exact error and Node version in a fresh issue. Thanks!
