### PR TITLE
Revert: Framework: Download api-request shim directly from GitHub

### LINKED ISSUE #3248: TypeError: wp.apiRequest is not a function
## Issue Overview
I've just installed Wordpress and Gutenberg. When trying to add / view a post / page I'm getting a blank screen and this error in the console. 

## Steps to Reproduce (for bugs)

1. Install latest Wordpress 4.8.2
2. Remove all plugins (Akismet, Hello Dolly)
3. Install and build the Gutenberg plugin on a local Wordpress Environment (https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md)
4. Try to add / edit posts or pages.

I'm using Firefox 56.0 on Ubuntu. Tested also in Chrome Version 62.0.3202.62 (Official Build) (64-bit) with the same result.
I'm using Node v8.1.2 and npm 5.3.0

## Expected Behavior

I've expected to see the new Gutenberg editor

## Current Behavior

I've got a blank page. See the screenshot attached: https://imgur.com/a/HwnFi

## Possible Solution

Perhaps Gutenberg needs WP-API which is not specified in the documentation / between dependencies

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by aduth**
Reverts WordPress/gutenberg#2705
Fixes #3248

This pull request reverts the change introduced by #2705 to reference the `wp.apiRequest` shim script directly from GitHub. While the logic to download a local copy of the shim from GitHub directly works correctly, the behavior of vendor scripts is such that if the download fails, the script is enqueued from its original resource:

https://github.com/WordPress/gutenberg/blob/be8d37ab7deab7baeef4eefe9b714c29c4e5cd09/lib/client-assets.php#L409-L412

Since GitHub does not allow hotlinking script resources directly on the githubusercontent.com domain, we should revert back to using the rawgit.com URL which, while not an "official" source, is intended for supporting hotlinking.

While using the fallback script is not desirable, it seems it may occur in environments such as those where file permissions do not allow for the downloaded script to be written.

__Open questions:__

- Per [documentation](http://rawgit.com/), should we use the production URL which is not updated as frequently? It was assumed using development link would not be an issue since it should ideally only be referenced once for the initial download, but if there are permissions issues preventing the vendor download, this file may be referenced often (though not in the plugin distributable, which included a pre-downloaded copy).

__Testing instructions:__

Repeat testing instructions from #3248

Verify that vendor script downloading works as expected.

1. Change into Gutenberg plugin directory: `cd path/to/gutenberg`
2. Empty contents of the vendor directory: `rm -f vendor/*`
3. Navigate to Posts > New Post
4. Note that Gutenberg loads correctly
5. Note that vendor scripts, including `api-request-*****.js` exists in your `vendor` directory

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]

**Review by gziolo — APPROVED** [review]
Looks good.

We could also copy this file to `vendor` folder to make it work until 4.9 is out :)

I'm trying to understand why we handle all of that vendor files using PHP instead of making this part of the build. It looks like caching mechanism was introduced in here: https://github.com/WordPress/gutenberg/pull/795, but from what I see at least half of the resources could be copied from `node_modules` folder. It would also help to keep `package.json` in sync with what we have specified in here.

**Comment by youknowriad** [comment]
Merging this to rebase the e2e tests PR

**Comment by aduth** [comment]
>from what I see at least half of the resources could be copied from `node_modules` folder.

What would we do for the other half?

**Comment by gziolo** [comment]
> What would we do for the other half?

Leave it as it is or handle it with node. I'm mostly concern about React and TinyMCE which should be always in sync.
