### ISSUE TITLE
Page became blank after update to 3.8.0 version

### ISSUE THREAD

**Issue by sanker2008** [WordPress/gutenberg#9990]
**Desktop (please complete the following information):**
 - Win10
 - Chrome
 - 3.8.0 version

Uncaught TypeError: wp.components.unstable__setSiteURL is not a function

Uncaught TypeError: Cannot read property 'parse' of undefined

ncaught TypeError: Cannot read property 'setCategories' of undefined

...
..
.

**Comment by designsimply** [comment]
Thank you for reporting this! I cannot see the same problem happen on my test site and it's possible you either have some different configuration settings that we need to know about in order to repeat the problem in a test or it's also possible there may be a plugin conflict.

Are you using a multisite install?

Since the first error mentions `setSiteURL` can you let us know if you are using custom settings for the `WordPress Address (URL)` and `Site Address (URL)` fields on your Settings > General page?

May I ask what plugins you have installed?

**Comment by designsimply** [comment]
I noticed similar errors reported at https://github.com/WordPress/gutenberg/issues/9845#issuecomment-420883106 and they mentioned that clearing browser cache and cookies solved the problem in that case. Can you try clearing your browser cache and cookies to see if that helps in your case?

Here is the screenshot and a copy of the errors from the other report for reference:

> Uncaught TypeError: Cannot read property 'parse' of undefined
> Uncaught TypeError: Cannot read property of 'setCategories' of undefined
> Uncaught TypeError: Cannot read property of 'normalizeIconObject' of undefined
> Uncaught TypeError: Object(...) is not a function
> Uncaught TypeError: Cannot read property 'registerCoreBlocks' of undefined

![image](https://user-images.githubusercontent.com/43229323/45467847-dcd24c80-b74b-11e8-8f1f-c95f471af148.png)

**Comment by sanker2008** [comment]
Thanks, I don't see the error logs today. Maybe is the browser cache and cookies problem.

**Comment by designsimply** [comment]
Thanks for the details @awayken. A 404 for `wp-polyfill-ecmascript.min.2ae96136.js` sounds odd to me. May I ask if you are using a server setup by a hosting service, and if so which host, or if you have setup your own server? In either case, do you know if there are any ModSecurity rules in place which could be blocking `wp-polyfill-ecmascript.min.2ae96136.js`?

@sanker2008 may I ask where your site is hosted?

**Comment by awayken** [comment]
@designsimply I am using a hosting service called [A Small Orange](https://asmallorange.com/). I don't know if there are ModSecurity rules in place or not. I use Cloudflare, too, mostly for the caching, but there are some other features enabled.

Would there be anything in the HTTP response that would tell me if ModSecurity is behind it? Do I just need to contact my host to find out if they're using it? Is there a workaround if that's the case?

**Comment by designsimply** [comment]
> Would there be anything in the HTTP response that would tell me if ModSecurity is behind it?

When I had a problem with a ModSecurity rule for a site hosted at Bluehost, I could see a 406 HTTP response in the console for the same file, but that code is a bit different—a 406 means "not acceptable" (in this case it was blocked by something) and a 404 means the file is not found. Let me document my case a with a bit more detail since it keeps coming up. Note: the following problem was found and fixed during 3.8.0-rc.1 (pre-release) testing which was posted at https://make.wordpress.org/test/tag/call-for-testing/

Problem:

- Mod_Sec was blocking `wp-polyfill-ecmascript.min.2ae96136.js` which prevented Gutenberg Posts > Add New from loading (fully white screen)

Steps to reproduce:

1. Download Gutenberg 3.8.0-rc.1 from https://github.com/WordPress/gutenberg/releases/tag/v3.8.0-rc.1
2. Go to Plugins > Add New > Upload Plugin and install the download.
3. Go to Posts > Add New.

Result: fully white screen with the following errors showing in the console.

> Failed to load resource: the server responded with a status of 406 () (wp-polyfill-ecmascript.min.2ae96136.js, line 0)
> ReferenceError: Can’t find variable: regeneratorRuntime
> TypeError: Object(G.withColors) is not a function. (In ‘Object(G.withColors)(“backgroundColor”,{textColor:”color”})’, ‘Object(G.withColors)’ is an instance of Object)
> TypeError: undefined is not an object (evaluating ‘Object(u.select)(“core/editor”).getBlockSelectionStart’)
> TypeError: undefined is not an object (evaluating ‘wp.editPost.initializeEditor’)

![screen-shot-2018-09-07-at-3-25-48-pm](https://user-images.githubusercontent.com/1119271/46216766-4fc3f180-c30e-11e8-9631-f1a5472656e3.png)
<sup>Seen at https://madefortesting.com/wp-admin/post-new.php running WordPress 4.9.8 and Gutenberg 3.8.0-rc.1 using Safari 11.1.2 on macOS 10.13.6.</sup>

Loading https://madefortesting.com/wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js directly in a browser returned:

> Not Acceptable!
> An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

![screen-shot-2018-09-07-at-3-46-12-pm](https://user-images.githubusercontent.com/1119271/46216854-7c780900-c30e-11e8-8034-f526de12d22b.png)
<sup>Seen at https://madefortesting.com/wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js using Safari 11.1.2 on macOS 10.13.6.</sup>

Tested with WordPress 4.9.8 and Gutenberg 3.8.0-rc.1 as the only installed/active plugin. There were also 4 Must-Use plugins which turned out to be unrelated to the problem.

Solution: we worked together with Bluehost systems administrators to get the problem fixed before 3.8 was released.

As you can see from trying to load the file from the first error directly in a browser, it gave a clear message that Mod_Security was the source of blocking that file.

> Do I just need to contact my host to find out if they're using it? 

You could, but it would be nicer if you had some evidence from either an error or a log that helps pinpoint the problem. Since you also said you are using Cloudflare, that could easily be the culprit as well. My goal is to help uncover the details that will get us to the right place and to a solution.

> Is there a workaround if that's the case?

Yes! In my case where a Mod_Security rule was blocking a needed file, so I contacted the host and they fixed the problem but updating the firewall rule that was blocking the file I needed. In your case we haven't uncovered an error that says "Mod_Security" specifically, so it could be some other thing that is blocking the file and they should be able to help you figure out what that is. I also noticed that another user reported the same problem at https://github.com/WordPress/gutenberg/issues/9979#issuecomment-422569762 and they are also using A Small Orange for hosting. The best way to ask them for help would be to tell them that you're seeing a 404 for /wp-content/plugins/gutenberg/vendor/wp-polyfill-ecmascript.min.2ae96136.js but that you need that file to be accessible and that it should be present on the server and could they help you check that and also check for why it might be returning a 404 when it should not.

I am going to close this issue for now because it does appear to be something to fix on the hosting side. I would love to hear back from you about an update when it gets fixed! And if you need any further help or notes about what details to gather or how to report the problem, please reply here and let me know.
