### PR TITLE
Fix pasting freeform content

### LINKED ISSUE #2008: Some pasted content crashes editor
## Steps to Reproduce

1. Copy a couple paragraphs of text from http://lipsum.com/feed/html
2. Paste into a new Gutenberg > New Post post text block

## Expected Behavior

Content is pasted.

## Current Behavior

Editor crashes.

[`Uncaught TypeError: text.replace is not a function`](https://github.com/WordPress/WordPress/blob/de31d6f/wp-admin/js/editor.js#L317)

(Note this is a core file, but the same error does not occur in the current post editor)

## Possible Solution

It's not yet clear to me whether there are hidden characters in the text that are causing issues. Pasting it into a plain text editor, then re-copying, then pasting into editor works as expected.

### PR DESCRIPTION
**Pull request by ellatrix**
Fixes #2008.

### CODE REVIEW

**Comment by iseulde** [comment]
Hm, not sure what's going wrong again here...

**Comment by iseulde** [comment]
Introduced in #1394, which changed the type of the block attribute.

**Review by aduth — DISMISSED** [review]
Lint errors caused by unused variables `nodeListToReact` and `createElement`, but I can confirm this fixes #2008. One other item I notice is that it might be nice to trim the pasted content. Copying from lipsum.com into a new post, for example, causes 2 empty paragraphs to linger. Also one stuck with placeholder event when not selected:

Placeholder

Should be okay to merge with lint issues addressed.

**Comment by iseulde** [comment]
Huh. I think I dreamed the tests passed on my side.

**Comment by iseulde** [comment]
> One other item I notice is that it might be nice to trim the pasted content. Copying from lipsum.com into a new post, for example, causes 2 empty paragraphs to linger. Also one stuck with placeholder event when not selected:

Sounds like something good to do in a separate PR. :)
