### PR TITLE
Fix pasting MS Word table

### LINKED ISSUE #42570: Raw Handling: Paste from MS Excel no longer creates a table block
### Description

Pasting content from Microsoft Excel as a table is not working as expected. I expect to content copied from an Excel spreadsheet to create a table block when pasted in the editor. Instead, it pastes as a paragraph block.

Copying and pasting from Google Sheets works as expected -- it creates a table block in the editor. But copying and pasting from Excel appears to strip the HTML during an intermediary step between pasting and block creation (see screen recording).

This issue _appears_ to have originated in v5.9, but I'm not sure. I used the "WP Downgrade | Specific Core Version" plugin to downgrade from 6.0.1 to 5.8.4 (my end users noticed the issue begin around March or April) and copy-paste from Excel works as expected in 5.8.4.

### Step-by-step reproduction instructions

1. Create an Excel spreadsheet with some content.
2. Go to Pages > Add New.
3. Copy the content of the Excel spreadsheet into the WP editor.
4. See error.

Repeat steps from Google Sheets to see expected behavior.

### Screenshots, screen recording, code snippet

On a fresh local WordPress 6.0.1 installation:

wp6-0-1-excel-table-format

### Environment info

- WordPress 6.0.1, not using Gutenberg plugin, default Twenty Twenty-One theme, and no plugins active. Issue appears in Twenty-Twenty Two theme as well, and when downgraded as far as WordPress 5.9.
- Firefox 102.0.1 (64-bit). Issue also appears in Chrome (103.0.5060.134) and Edge (103.0.1264.62).
- Desktop with Windows 10.
- WordPress running in local Docker environment. Issue also appears in WP 6.0.1 running in hosted environment.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #42570.

Pasting tables (and potentially other stuff) from MS Word is broken because everything before and and after the StartFragment/EndFragment comments is stripped.

This is a regression caused by #33607.

## How?

The solution is to reuse the battle tested strippers from the paste handler instead of doing something different.

### CODE REVIEW

**Comment by t-hamano** [comment]
Thanks for the PR!

When I tried to paste from Excel, the following error appeared in the browser console.

```
use-paste-handler.js:46 Uncaught TypeError: (0 , _wordpress_blocks__WEBPACK_IMPORTED_MODULE_2__.getClipboardEventData) is not a function
    at HTMLParagraphElement._onPaste (use-paste-handler.js:46:60)
```

Therefore, I added a process to export `getClipboardEventData` and rebuilt the document. Please feel free to correct me if my approach is incorrect.

**Review by t-hamano — COMMENTED** [review]
This PR works correctly for me!

### Copy from Google docs (spreadsheet)

- ✅ Normal table
- ✅ Table with merged cells

### Copy from MS Word

- ✅ Normal table
- ✅ Table with merged cells

### Others

I also tested whether the issue fixed in #33607 caused a regression.

- ✅ When you copy and paste inline text, there are no spaces at either end.
- ✅ If you intentionally copy and paste text that contains spaces, spaces will remain.

https://github.com/WordPress/gutenberg/assets/54422211/a73a3fe1-93fb-421a-85bd-75386d7d12bb

I would be happy if this PR could address the following two things:

- Add raw-handling test (Like `ms-excel-table-in|out.html` for example?)
- I think this PR will expose `getPasteEventData()` function, so how about adding JSDoc so that it is reflected in the README?

**Comment by ellatrix** [comment]
Yes, I'll add a test, and I'll lock the function as a private api for now

**Comment by t-hamano** [comment]
This latest PR appears to re-introduce the issue fixed in #33607.

https://github.com/WordPress/gutenberg/assets/54422211/61ce8e9a-068e-4580-a3c0-fec77763453c

For example, if I copy and paste the word "WordPress" from within a paragraph block, the HTML before filtering will look like this:

```
<html>
<body>
<!--StartFragment-->WordPress<!--EndFragment-->
</body>
</html>
```

It looks like it's probably because there's an extra text node before `StartFragment` or after `EndFragment`. I think we may need to remove this unnecessary text node, for example like below:

```javascript
export default function msFragmentRemover( node ) {
	if (
		node.nodeType === node.COMMENT_NODE &&
		[ 'StartFragment', 'EndFragment' ].includes( node.textContent.trim() )
	) {
		// Remove unnecessary text nodes before StartFragment or after EndFragment.
		const textNode =
			node.textContent.trim() === 'StartFragment'
				? node.previousSibling
				: node.nextSibling;
		if ( textNode && textNode.nodeType === textNode.TEXT_NODE ) {
			remove( textNode );
		}
		// Remove the fragment comment node.
		remove( node );
	}
}
```

File: test/integration/fixtures/documents/ms-excel-in.html [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+xmlns="http://www.w3.org/TR/REC-html40">
+
+<head>
+<meta http-equiv=Content-Type content="text/html; charset=utf-8">
+<meta name=ProgId content=Excel.Sheet>
+<meta name=Generator content="Microsoft Excel 15">
+<link id=Main-File rel=Main-File
+href="file:///C:/Users/TETSUA~1.HAM/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
+<link rel=File-List
+href="file:///C:/Users/TETSUA~1.HAM/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
```
Comment (t-hamano) [inline test/integration/fixtures/documents/ms-excel-in.html]:
```suggestion
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
```

Let me replace my name with a dummy user 😅
