### ISSUE TITLE
getBoundingClientRect error in Popover Component for anchorRef prop

### ISSUE THREAD

**Issue by bfintal** [WordPress/gutenberg#19154]
**Describe the bug**
Popover's `anchorRef` prop throws the following error when passed a prop:

> Uncaught TypeError: r.getBoundingClientRect is not a function

**To reproduce**
I have a button, that when clicked opens a Popover Component. A `ref` to the button is passed in the Popover's `anchorRef` prop. Here's the trimmed down Component with the relevant code:

```js
class ButtonIconPopoverControl extends Component {
	constructor() {
		super( ...arguments )
		this.buttonRef = createRef()
	}
	render() {
		return (
			<BaseControl>
				<IconButton ref={ this.buttonRef } />
				{ this.state.open && (
					<Popover anchorRef={ this.buttonRef } />
				) }
			</BaseControl>
		)
	}
}
```

This works fine in WordPress 5.3.x. Turning on Gutenberg 7.1.0 throws the error on `getBoundingClientRect()`: https://github.com/WordPress/gutenberg/blob/bd8436f9f94656e8adc00dc1fdb3bbc6307f00af/packages/components/src/popover/index.js#L65

Related: #17867

**Expected behavior**
No error

**Additional context**
- Okay in WordPress 5.3.1
- Error on Gutenberg plugin 7.1.0

**Comment by talldan** [comment]
@bfintal It looks like the correct code would be:
```
<Popover anchorRef={ this.buttonRef.current } />
```

It's not very clear that this is the case. I couldn't see any docs for this prop, so would be happy to consider this issue as a need to update the component's README.

**Comment by bfintal** [comment]
I see. I guess the confusion was that since the prop was called `anchorRef` I assumed that all I needed to pass was the actual reference. I'm good with the clarification in the documentation

**Comment by ellatrix** [comment]
Sorry about the confusion. Naming it ref(erence) was maybe a bit too broad. In this case it's the element (or range) reference.
