### ISSUE TITLE
Tests fail when run under Node v6.10.2 or earlier

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#414]
Regression introduced in #399 (a71bea2)

__Steps to reproduce:__

1. Install Node v6.10.2 (easiest with [n](https://www.npmjs.com/package/n) or [nvm](http://nvm.sh/))
2. Run `npm run test-unit`

__Expected result:__

Tests pass, especially considering we [define a preferred version via `.nvmrc`](https://github.com/WordPress/gutenberg/blob/master/.nvmrc).

__Actual result:__

Tests fail with error:

```
TypeError: Object.values is not a function
```

__Anticipated cause:__

Support for the `Object.values` function was not added until Node 7.x . 

See also: http://node.green/#ES2017-features-Object-static-methods-Object-values

Removing the `transform-runtime` Babel plugin from the test build means that this method is not polyfilled. We'll need to consider how to reconcile this with the Babel issue described here:

https://github.com/babel/babel/issues/2877#issuecomment-270700000

**Comment by aduth** [comment]
Related to this, our Travis configuration should probably be such that it aligns with the version defined in `.nvmrc` if this is the version we want to assign as "preferred".

**Comment by nylen** [comment]
After `nvm install 7` (which put me on version 7.9.0), I had to run `npm rebuild node-sass` to make the build/tests work.

**Comment by youknowriad** [comment]
Closing as fixed
