### ISSUE TITLE
Blank screen on editor pages after updating Gutenberg to 4.0.0

### ISSUE THREAD

**Issue by joelcieslar** [WordPress/gutenberg#10857]
**Describe the bug**
Since updating Gutenberg to 4.0.0, I am presented with a blank screen when attempting to create/edit posts.

**To Reproduce**
1. Go to Posts > Add New
2. Blank screen.

**Expected behavior**
The WordPress interface and Gutenberg editor should load and allow me to compose a new post.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14)
 - Browser: Chrome 70.0.3538.67 (64-bit)

**Additional context**
This error is present in the console:

```
index.js?ver=1540124178:1 Uncaught TypeError: t is not a function
    at Object.use (index.js?ver=1540124178:1)
    at post-new.php:123
    at post-new.php:125
```

**Comment by youknowriad** [comment]
Do you have any Gutenberg custom blocks or plugins on your site?

**Comment by joelcieslar** [comment]
No custom blocks (as far as I know), and I'm using the following plugins:

- Gutenberg
- Maintenance Mode
- Nginx Helper
- Smush
- Speed Booster Pack
- W3 Total Cache

I've tried clearing my browser cache and disabling plugins to no avail.

**Comment by joelcieslar** [comment]
@swissspidy I'm using the latest version - WordPress 4.9.8.

**Comment by rkcrane11** [comment]
I am also experiencing this issue, same configuration settings as @joelcieslar 

Desktop (please complete the following information):

OS: MacOS Mojave (10.14)
Browser: Chrome 70.0.3538.67 (Official Build) (64-bit) 

I have already gone and disabled all plugins and re-enabled them. The only one that cause the page not to load is Gutenberg. 

I would disable it, but then all of my previously posted posts are formatted incorrectly (galleries become bulleted lists).

This issue does appear to be unique to Google Chrome, as everything loads correctly in Safari. Note: Chrome appears to be having issues with it in general, as it is having issues with loading things in other sites, such as Youtube where the editors won't load.

**Comment by mikesale** [comment]
I can confirm this is unique to Chrome as this problem does not occur in Safari on the same machine.

**Comment by designsimply** [comment]
@joelcieslar are you able to test whether or not the issue persists for you if you try with Safari? Also, would you be okay to try temporarily deactivating the Nginx Helper plugin as a troubleshooting step to rule out a conflict there?

@rkcrane11 can you confirm the error message you're seeing in the Console panel in Chrome's developer tools?

**Comment by joelcieslar** [comment]
Just tested with Gutenberg 4.3.0 - everything seems to be working fine. Using Chrome with Nginx Helper activated :)

**Comment by rkcrane11** [comment]
All is working well for me as well after the update. 

Rachel

2018. 11. 13. 오후 7:42, Joel Cieslar <notifications@github.com> 작성:

**Comment by HeirWavStudios** [comment]
Had this problem for a while now and even still after updating to 4.6. I have tested all plugins and Gutenberg is the only one that causes this problem.

**Comment by designsimply** [comment]
Thank you for the follow-ups!

@HeirWavStudios if you are still having trouble, may I please ask that you start a new issue and mention your current WordPress version as well as confirm what error you are seeing in the browser console when the error appears?
