### PR TITLE
core-data: Fix nested property access with undefined name

### LINKED ISSUE #54735: Regression: Error when using nested properties in `_fields` with `getEntityRecord()`
### Description

When requesting something from the REST API using `wp.data.select('core').getEntityRecord()` this can result in an uncaught Type Error.

I noticed this when trying to get back the routes field removed in https://github.com/WordPress/gutenberg/pull/39256/files#diff-38a74d088ea018dbbea00d8f5bd5c03ea54bfc099d1d1836686c24a5582bf579R27-R39 using the [`_fields` parameter](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields).

Here is an example. Just run this code in the console when editing a post:

```
wp.data.select('core').getEntityRecord()'root', '__unstableBase', undefined, { _fields: [ 'routes./wp/v2/posts' ] })
```

Yes, I know, I am using `__unstableBase` here which is a private API. But please still hear me out since the surfaced issue is a fundamental bug that probably can also occur in other situations. I just wasn't able to find another example quickly now.

---

I think this issue appeared when removing Lodash `_.get()` in https://github.com/WordPress/gutenberg/commit/4b12c75df261f62c7ca5312c900628920338b16b#diff-6fae435c7327c5edb1a67718054b7ee8513d4691a19b416e7d5f628aefc4459bR69-R72 of #48310.

The problem is that using the dot syntax to limit the retrieved data to a nested property tries to get a property of `undefined` here when first requesting the data:

https://github.com/WordPress/gutenberg/blob/a5a32c1da19589a60d48ae793a3d0a5a48223db6/packages/core-data/src/queried-data/selectors.js#L71

which fails with the Type Error mentioned above.

This is also confirmed by the fact that the following runs flawlessly:

```
wp.data.select('core').getEntityRecord('root', '__unstableBase', undefined, { _fields: [ 'routes' ] })
```

The old implementation with Lodash `_.get()`

https://github.com/WordPress/gutenberg/blob/e086b2b595618a5f4c9491119695be3e074d736b/packages/core-data/src/queried-data/selectors.js#L69

though [would handle this edge case](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L13126-L13129) returning `undefined` instead of causing a Type Error in both cases.

---

So as a solution I'd assume an additional check for `undefined` would solve this issue. Something along the lines of

```
value = typeof value === 'undefined' ? undefined: value[fieldName];
```

Which a quick check altering WP 6.3 core confirmed.

### Step-by-step reproduction instructions

1. Open the block editor
2. Run `wp.data.select('core').getEntityRecord()'root', '__unstableBase', undefined, { _fields: [ 'routes./wp/v2/posts' ] })` in the console
3. See a "Uncaught TypeError: value is undefined".

1. Open the block editor (reload, doesn't work when the data has been requested before)
2. Run `wp.data.select('core').getEntityRecord()'root', '__unstableBase', undefined, { _fields: [ 'routes' ] })` in the console
3. See no error but a value of `undefined` returned.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.3
- no Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tyxla**
## What?
This PR fixes a [regression](https://github.com/WordPress/gutenberg/issues/54735) we introduced in https://github.com/WordPress/gutenberg/pull/48310 when migrating away from `_.get()`.

The issue is thoroughly explained in #54735.

Fixes #54735, cc @kraftner.

## Why?
Fixes an issue with how we're handling `getEntityRecord()` calls with `undefined` `name`s.

## How?
We're adding optional chaining so entities with `undefined` name won't throw an error.

## Testing Instructions
* Build this branch locally
* Run `wp.data.select( 'core' ).getEntityRecord( 'root', '__unstableBase', undefined, { _fields: [ 'routes./wp/v2/posts' ] } )` in your console.
* Verify you don't get any errors.

### Testing Instructions for Keyboard
None.

## Screenshots or screencast 
None.

### CODE REVIEW

**Comment by kraftner** [comment]
Looking at #48310 I also just noticed https://github.com/WordPress/gutenberg/pull/48310/files#diff-c9806943cd2157856848ecea1d5d7f97f6bd462827ed87b246be86c758f684f8R337

I am unsure what the connection between the JS and TS files is, but this looks very similar:

https://github.com/WordPress/gutenberg/blob/61736f4a7431b3ac9b511c5c3e6ed63d0b350f8e/packages/core-data/src/selectors.ts#L347

Might this be related and also need a fix?

**Comment by Mamaduka** [comment]
@kraftner, both paths have been fixed in this PR.

**Comment by kraftner** [comment]
Sorry, my brain apparently just misfired overlooking the second change. :zany_face: Sorry for the noise. :grimacing:

**Review by Mamaduka — APPROVED** [review]
Works as expected ✅ 

The regression was introduced in WP 6.3, I'm tentatively marking this for backport in next major release.

Sidenote: It might be a good idea to introduce more high-level tests for core data selectors. There have been previous cases when unit tests were insufficient to catch regressions like this.

File: packages/core-data/src/selectors.ts [hunk 1]
```diff
@@ -344,7 +344,7 @@ export const getEntityRecord = createSelector(
 				const field = fields[ f ].split( '.' );
 				let value = item;
 				field.forEach( ( fieldName ) => {
-					value = value[ fieldName ];
+					value = value?.[ fieldName ];
```
Comment (jsnajdr) [inline packages/core-data/src/selectors.ts:347]: Could be nice to abort early when `value` becomes `undefined`. Also, this can be a good use of `reduce`:
```js
const value = fields.reduce( ( v, f ) => v?.[ f ], item );
```
But the early abort probably requires a `for` loop with `break` anyway.

Comment (tyxla) [reply packages/core-data/src/selectors.ts:347]: I agree, but FWIW I opted for brevity here. And I think we no longer need to abort early since we're covering `undefined` with the optional chaining.

**Comment by tyxla** [comment]
> It might be a good idea to introduce more high-level tests for core data selectors. There have been previous cases when unit tests were insufficient to catch regressions like this.

I agree. 👍 

I've added a unit test that covers this particular scenario in https://github.com/WordPress/gutenberg/pull/54790/commits/de11c8784d716e915af60a129337bc8542bf7797 but it might be a good idea to add some more tests in the future.

**Comment by mikachan** [comment]
I just cherry-picked this PR to the release/16.7 branch to get it included in the next release: 084cfc238e
