### PR TITLE
Try block toolbar inline edit slot

### PR DESCRIPTION
**Pull request by talldan**
## Description
Reverts #23613 and replaces it with a 'popover' style slot as advised by the a11y team in https://github.com/WordPress/gutenberg/pull/24021#issuecomment-687827684.

## How does this work?

This PR introduces a new slot on the toolbar `BlockToolbarInlineEditSlot`. When this slot contains a fill, it signals to a context provider that other toolbar content should be 'visually hidden' and only the fill should be rendered.

Additionally, anything rendered in the fill is wrapped in a `PopoverWrapper` (the same as the one introduced in https://github.com/WordPress/gutenberg/pull/24429) which provides popover behaviors but is rendered inline.

## How has this been tested?
This PR doesn't actually implement anything visible, but I've rebased #24021 on top of this, and that's the PR should be tested.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by afercia** [comment]
I'm no table to build this branch, getting a huge dump of errors apparently related to TypeScript and SVGs, see example below. Any idea what's going wrong?

```
packages/icons/src/library/trending-up.js:8:4 - error TS2741: Property 'path' is missing in type '{ d: string; }' but required in type 'Pick<SVGProps<SVGPathElement>, "string" | "end" | "local" | "color" | "clip" | "style" | "fill" | "stroke" | "x" | "y" | "alphabetic" | "hanging" | "ideographic" | ... 455 more ... | "zoomAndPan">'.

8  	<Path d="M3.445 16.505a.75.75 0 001.06.05l5.005-4.55 4.024 3.521 4.716-4.715V14h1.5V8.25H14v1.5h3.19l-3.724 3.723L9.49 9.995l-5.995 5.45a.75.75 0 00-.05 1.06z" />
   	 ~~~~


Found 372 errors.
```

**Comment by talldan** [comment]
Superseded by #25890
