### ISSUE TITLE
Navigation Editor: Unresponsive "Start Blank" and "Add all pages" buttons. Unable to add pages. 

### ISSUE THREAD

**Issue by mrfoxtalbot** [WordPress/gutenberg#37699]
### Description

The Navigation **_Editor_** (beta) has two options to add pages, `Start Blank` and `Add all pages` but neither of them seems to be responding.

### Step-by-step reproduction instructions

Firstly [follow steps here to enable the experiment](https://github.com/WordPress/gutenberg/issues/37699#issuecomment-1004746336).

1. Go to `/wp-admin/admin.php?page=gutenberg-navigation`.
2. Create a new menu.
3. Try to add pages by either of the two methods mentioned above.
4. Nothing happens :(

### Screenshots, screen recording, code snippet

![Kapture 2022-01-04 at 01 08 51](https://user-images.githubusercontent.com/4452464/147993480-00ad69c6-325d-4e6d-8df7-1987d0d1ff52.gif)
 

### Environment info

- WordPress 5.8.2 running Twenty Nineteen theme.
- Gutenberg plugin version 12.2.0.
- No other active plugins.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes, No

**Comment by mrfoxtalbot** [comment]
I noticed the problem above alongside this other separate bug https://github.com/WordPress/gutenberg/issues/37698

**Comment by carolinan** [comment]
Hi, where does this admin path come from?

**Comment by mrfoxtalbot** [comment]
Hi @carolinan! For this path to become available, the `Enable Navigation Screen` option needs to be checked, under "Experiments" at `wp-admin/admin.php?page=gutenberg-experiments`

![Screen Shot on 2022-01-04 at 12:53:07](https://user-images.githubusercontent.com/4452464/148055320-f14374be-6974-47aa-8046-4d31218129b5.png)

I have never reported a bug about an experimental feature, so please do let me know if there is a separate process for this.

Thank you!

**Comment by Mamaduka** [comment]
It looks like a regression after #35746.

This is the error, I'm getting when running in dev mode:

```
index.js:93 Uncaught TypeError: onCreate is not a function
    at onCreateEmptyMenu (packages/edit-navigation/src/components/block-placeholder/index.js:93:3)
```

**Comment by mrfoxtalbot** [comment]
@Mamaduka, could you please confirm if this issue is now solved so we can close it? Thank you!

**Comment by Mamaduka** [comment]
@mrfoxtalbot, I don't believe so. Navigation Screen needs to be synced with some recent changes in Navigation Block.

cc @getdave

**Comment by getdave** [comment]
Thanks for the report! 

The Nav screen is still experimental and needs updating to catch up with changes. 

It will be updated based on feedback from WP 5.9.

**Comment by mrfoxtalbot** [comment]
I was trying to reproduce this error but I in `13.7.2` I am no longer able to access this URL `/wp-admin/admin.php?page=gutenberg-navigation` and the "Enable Navigation Screen" setting under "Experiments" is now gone:

![Screen Shot on 2022-07-25 at 11:58:10](https://user-images.githubusercontent.com/4452464/180750920-927b6a32-6d30-4a70-a902-365c4a6fde76.png)

I am going to close this as "Cannot Reproduce" for now but if you have a moment @getdave, could you please confirm that this is no longer a problem? Thank you!

**Comment by getdave** [comment]
We've removed this screen from experiments so the bug no longer exists.
