### ISSUE TITLE
Why doesn't this work in 2.9?

### ISSUE THREAD

**Issue by NathanDJohnson** [WordPress/gutenberg#6837]
This code worked in 2.8. What changed? Because the documentation sure didn't.

```
const { registerBlockType, RichText } = wp.blocks;

registerBlockType( 'test/test', {
    title: 'Test',
    icon: 'universal-access-alt',
    category: 'layout',

    attributes: {
        content: {
            type: 'array',
            source: 'children',
            selector: 'p',
        },
    },

    edit( { attributes, className, setAttributes } ) {
        const { content } = attributes;

        const onChangeContent = newContent => {
            setAttributes( { content: newContent } );
        };

        return (
            <div className={ className }>
                <RichText
                    tagName="p"
                    placeholder={ 'Page Content' }
                    value={ content }
                    onChange={ onChangeContent }
                />
            </div>
        );
    },
    save( { attributes, className } ) {
        const { content } = attributes;

        return (
            <div className={ className }>
            <p>{ content }</p>
            </div>
        );
    },
} );
```

**Comment by youknowriad** [comment]
Sorry for the breakage. What's the javascript error you're seeing? Also how are you enqueuing the block on the server?

**Comment by NathanDJohnson** [comment]
```
react-dom.min.0d9b4499.js:62 Error: Minified React error #130; visit http://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ze (react-dom.min.0d9b4499.js:82)
    at l (react-dom.min.0d9b4499.js:12)
    at ec (react-dom.min.0d9b4499.js:46)
    at react-dom.min.0d9b4499.js:61
    at k (react-dom.min.0d9b4499.js:129)
    at h (react-dom.min.0d9b4499.js:129)
    at beginWork (react-dom.min.0d9b4499.js:138)
    at e (react-dom.min.0d9b4499.js:168)
    at f (react-dom.min.0d9b4499.js:169)
    at A (react-dom.min.0d9b4499.js:175)
    at t (react-dom.min.0d9b4499.js:174)
    at x (react-dom.min.0d9b4499.js:173)
    at interactiveUpdates (react-dom.min.0d9b4499.js:181)
    at Cd (react-dom.min.0d9b4499.js:40)
```

```
function enqueueBlockEditorAssets() {
  \wp_enqueue_script(
    'test',
    \get_stylesheet_directory_uri() . '/test.js',
    [ 'wp-blocks', 'wp-i18n', 'wp-element' ]
  );
}
\add_action( 'enqueue_block_assets', __NAMESPACE__ . '\enqueueBlockEditorAssets' );
```

**Comment by youknowriad** [comment]
Try adding `wp-editor` to the dependencies of your script?

**Comment by NathanDJohnson** [comment]
That fixed it. Thanks. Not sure why 2.9 requires that but not 2.8.

**Comment by youknowriad** [comment]
So we moved stuff from `wp.blocks` to `wp.editor` which means script need to depend on `wp-editor` instead of `wp-blocks`. We thought that we thought that we got backwards compatibility right but apparently we broke some plugins that load their scripts "early" (before `wp-editor` is loaded), I'll see what we can do to limit this breakage.

**Comment by robertdevore** [comment]
Don't mean to thread hijack but ran into something like this with another plugin.

Based on your description above, it looks like its because its registered on init right?

https://github.com/imtiazrayhan/Ultimate-Blocks/blob/master/src/blocks/click-to-tweet/block.php#L64

**Comment by youknowriad** [comment]
@robertdevore I think that's a different issue. It's a PHP issue while this one is JavaScript. I've just tried the last released version of the plugin you shared and it works for me.

**Comment by bryancasler** [comment]
Shared the experience going from 2.8 to 2.9 and getting similar error messages as Nathan, however not using any custom Plugins. Plus a search for "wp.blocks" across all installed plugins doesn't return any results outside the Gutenberg folder.

The page editor loads and its contents flash before the error message appears and takes over. While the page is loading, if I stop it prematurely after the content loads but before the error message appears, I can still use the full editor without issue (recording: [https://d.pr/v/MGjtxX](https://d.pr/v/MGjtxX)). Then if I then make a change to the post and click "Update" in the editor it will now continues to load without issue.

`TypeError: t.filter is not a function
    at t.<anonymous> (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/build/editor/index.js?ver=1527369203:12:170721)
    at Rd (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:49:248)
    at qb (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:50:350)
    at updateClassInstance (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:126:301)
    at beginWork (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:136:179)
    at e (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:168:321)
    at f (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:169:74)
    at A (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:175:8)
    at t (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:174:69)
    at x (https://dev-4site-gutenberg.pantheonsite.io/wp-content/plugins/gutenberg/vendor/react-dom.min.0d9b4499.js:173:417)`
