### ISSUE TITLE
Adding spacer block in 12.3.0 fails

### ISSUE THREAD

**Issue by evaldivieso** [WordPress/gutenberg#37758]
### Description
 
Seems like the latest updates to the spacer block is causing a bug, after I applied the latest Gutenberg plugin updates (12.3.0) this week I started to see the below message after insert the spacer block:

> This block has encountered an error and cannot be previewed.  

This just started happening this week, last week I've been using the spacer block fine.

### Screenshots, screen recording

![SS 2022-01-06 at 12 30 21 PM](https://user-images.githubusercontent.com/38438671/148425447-672c6583-c639-4250-a9e4-efb52d7093d9.png)

https://user-images.githubusercontent.com/38438671/148427901-17852938-6ba4-45c0-a9f2-d28c06522f6c.mp4

`TypeError: (0,Oe.useSetting)("spacing.units").filter is not a function. (In '(0,Oe.useSetting)("spacing.units").filter((e=>"%"!==e))', '(0,Oe.useSetting)("spacing.units").filter' is undefined)`

`The above error occurred in the <Ah> component:`

I also tried uninstalling the Gutenberg 12.3.0 plugin and installing the Gutenberg 12.2.0 and the spacer was working fine, I then updated to latest 12.3.0 version and run into the same issue.

Can someone please confirm and provide info for this issue. Thanks

**Comment by annezazu** [comment]
Thanks for reporting @evaldivieso ! How strange. I was able to replicate but only with certain themes.

- Spacer block works with Twenty Twenty-Two, Twenty Twenty-One,
- Spacer block doesn't work with Twenty Nineteen, Twenty Twenty, Twenty Seventeen.

Adding this as a regression to be looked into further. The above was confirmed with 5.9 RC1 as well so adding to the 5.9 board.

**Comment by Mamaduka** [comment]
I think the issue was introduced by #36186.

**Comment by Mamaduka** [comment]
@annezazu, I'm not able to reproduce the issue with 5.9 RC1 if I disable the Gutenberg plugin.

**Comment by annezazu** [comment]
Tried on a fresh install (that never had GB installed) with RC1 and can see it works fine with 5.9 RC1 :) Have another test site that can replicate but seems to be isolated. Removing from 5.9 must haves.
