### ISSUE TITLE
Images and embeds do not work

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#7707]
**Describe the bug**
Image and embed blocks added to the page will cause an error and the following browser console output `TypeError: "this.props.forwardedRef is not a function"`

**To Reproduce**
1. Edit a post or create a new post
2. Add an image block
3. Select an element from the media library

**Expected behavior**
You see the image.

**Screenshots**
![2018-07-04 15 08 05](https://user-images.githubusercontent.com/90871/42281731-582878d8-7f9c-11e8-97c6-494090eb4dce.gif)

Happens on master.

**Comment by tofumatt** [comment]
(Worried that e2e tests didn't catch this one 😓)

**Comment by tofumatt** [comment]
8b21632c90b4e5d1d155fa84312149c8687d1b5b is the problem commit says `git bisect`

**Comment by tofumatt** [comment]
Going back to the check for `this.props.forwardRef` used in https://github.com/WordPress/gutenberg/pull/6261#discussion_r198187394 "fixes" it, which indicates the ref forwarding isn't working or as [@aduth mentioned in Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1530713258000140) might not be working when no refs are assigned to be forwarded...

**Comment by nerrad** [comment]
Ya the issue here is that there is probably something else using `withGlobalEvents` that is not setting a ref which gets forwarded.  So there _must_ be a check to see if there is a forwarded ref before acting on it.  Definitely the solution is to add back in the `if ( this.props.forwardedRef )` check in `handleRef`.

**Comment by tofumatt** [comment]
Yeah after running through the code that still seems to be the best option, and I can't see it breaking anything. Patch incoming...
