### ISSUE TITLE
Block Editor Not Working in Wordpress 5.5.1

### ISSUE THREAD

**Issue by harshk0525** [WordPress/gutenberg#25271]
### **Block Editor not working after updating to Wordpress 5.5.1**

Gives the following error:

```
Error: An error occurred while running 'mapSelect': e(...).getEntityRecordChangesByRecord is not a function
The error may be correlated with this previous error:
TypeError: e(...).getEntityRecordChangesByRecord is not a function
    at Object.current (https://uniformapp.in/blog/wp-includes/js/dist/editor.min.js?ver=1b4e724c353c8156e7987cc825fcf6d6:12:71041)
    at e (https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:24561)
    at https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:24726
    at https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:18650
    at Array.forEach (<anonymous>)
    at o (https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:18622)
    at https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:15849
    at p (https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:7909)
    at https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:9895
    at Object.dispatch (https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:10330)

Original stack trace:
    at Ge (https://uniformapp.in/blog/wp-includes/js/dist/data.min.js?ver=75f90354ddff4acd5b0b4026454037ca:2:24353)
    at Xo (https://uniformapp.in/blog/wp-includes/js/dist/editor.min.js?ver=1b4e724c353c8156e7987cc825fcf6d6:12:71010)
    at je (https://uniformapp.in/blog/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:78:476)
    at qe (https://uniformapp.in/blog/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:89:115)
    at ph (https://uniformapp.in/blog/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:216:489)
    at lh (https://uniformapp.in/blog/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:126:409)
    at O (https://uniformapp.in/blog/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:121:71)
    at ze (https://uniformapp.in/blog/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118:14)
    at https://uniformapp.in/blog/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:53:49
    at unstable_runWithPriority (https://uniformapp.in/blog/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26:340)
```

Screenshots
![image](https://user-images.githubusercontent.com/23427795/92999256-17d70880-f53d-11ea-83e7-265d9e48a7f9.png)

Editor version:
- WordPress version: 5.5.1
- Block editor: default
- Theme: Hestia

Fixes Tried:
- Installed Health Check plugin to disable all plugins and switch to default theme in Troubleshoot mode. Did not solve the issue.
- Already tried disabling all plugins and changing theme to a default theme as well. Did not solve the issue.
- Classic Editor is working.
- Tried disabling Yoast SEO and other plugins that embed code in the block editor. Did not solve the issue.

**Comment by senadir** [comment]
I couldn't reproduce the issue on a local website or a live website. Can you try reinstalling WordPress? 
Tested on WP 5.5.1 with included GB running Chrome 85, what browser are you running?

**Comment by harshk0525** [comment]
The issue arised due to Cloudflare being enabled at the time of update and Cloudflare cache not being deleted.
