### ISSUE TITLE
window.moment(...).tz is not a function error after updating to Gutenberg 9.4

### ISSUE THREAD

**Issue by chvillanuevap** [WordPress/gutenberg#27159]
**Describe the bug**
I have a JS function in my plugin:
`const currentDate = timestamp ? window.moment.unix( timestamp ).tz( 'WP' ).format( 'YYYY-MM-DD HH:mm' ) : window.moment().tz( 'WP' ).format( 'YYYY-MM-DD HH:mm' );`

It was working correctly and giving the current date until I updated to Gutenberg 9.4. Now I get an error that says `window.moment(...).tz is not a function` in the developer console.

**To reproduce**
1. Open the developer console.
2. Type window.moment().tz. See error.
3. It does work with Gutenberg 9.3.

**Expected behavior**
I'm not sure what changed from 9.3 to 9.4 with the moment function.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin.
- If the Gutenberg plugin is installed, which version is it? 9.4.1

**Comment by gziolo** [comment]
Can you verify whether your plugin defines `moment` script as one of your dependencies?

**Comment by chvillanuevap** [comment]
Thank you for your quick reply! I did include the script as a dependency when debugging, but it still would not work. I hadn't included the script as a dependency before, when using Gutenberg 9.3, but it did work fine then.

I don't think it is an issue regarding the enqueueing order because the function `window.moment(...).tz` is not defined in the developer console in Google Chrome, which should be free from ordering issues.

I think `tz` is part of a subpackage called `moment-timezone` (see [here](https://momentjs.com/timezone/)). Is this script not included with Gutenberg anymore perhaps? Based on #25782, should I not use `moment` anymore?

**Comment by vcanales** [comment]
Thank you @chvillanuevap for reporting, and @gziolo for the much needed context.

I created [this PR](https://github.com/WordPress/gutenberg/pull/27184) with the following in mind:

- Given that `moment` is being provided by WordPress directly into the `window` object, I think we need to restore the moment locale and timezone initialization previously available in order to prevent failure for other plugin developers who might depend on the site's timezone on the frontend.
- I've exported `@wordpress/date`'s `getTimezone` function in order to allow using the package to obtain the site's timezone in the future.
- Part of [this issue](https://github.com/WordPress/gutenberg/issues/26862) will require exporting much of `date-fns`'s functionality (if not all) through `@wordpress/date`, so after that is done, it would be a good idea to encourage other plugin developers to make the move to using `wp.date` in order to access date functions directly on the browser.

**Comment by chvillanuevap** [comment]
Thank you for that! If I understand correctly, the `wp.date` package does not have this functionality yet, and your PR probably won't get merged until 9.5, so my only option to fix my block right now would be to enqueue my own `moment.js` script, right?

**Comment by gziolo** [comment]
@chvillanuevap, thank you for all the details shared, it was very helpful to identify what has regressed.

> I think `tz` is part of a subpackage called `moment-timezone` (see [here](https://momentjs.com/timezone/)). Is this script not included with Gutenberg anymore perhaps? Based on #25782, should I not use `moment` anymore?

We need to find a way to make it work when plugins depend on `moment` directly, so while it should be fine to leave your plugin unchanged, I recommend trying to port your functionality to `@wordpress/date`. Moment.js is no longer actively maintained (see https://momentjs.com/docs/#/-project-status/) and in addition to that, the library that @vcanales integrated is much smaller so it decreased the number of data that needs to be downloaded in the browser.

**Comment by vcanales** [comment]
Closing this as fixed on https://github.com/WordPress/gutenberg/pull/27550
