### ISSUE TITLE
Typescript error is preventing the building of Gutenberg project

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#64002]
### Description

```
:~/dev/gutenberg$ npm run dev

> gutenberg@18.9.0-rc.1 dev
> cross-env NODE_ENV=development npm run build:packages && concurrently "wp-scripts start" "npm run dev:packages"


> gutenberg@18.9.0-rc.1 prebuild:packages
> npm run clean:packages && lerna run build


> gutenberg@18.9.0-rc.1 clean:packages
> rimraf "./packages/*/@(build|build-module|build-style)"

lerna notice cli v7.1.4
lerna info versioning independent
 
    ✔  @wordpress/block-serialization-spec-parser:build (423ms)
    ✔  @wordpress/babel-preset-default:build (2s)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Successfully ran target build for 2 projects (2s)
 

> gutenberg@18.9.0-rc.1 build:packages
> npm run --silent build:package-types && node ./bin/packages/build.js

packages/components/node_modules/framer-motion/dist/index.d.ts:1203:11 - error TS2430: Interface 'CSSStyleDeclarationWithTransform' incorrectly extends interface 'Omit<CSSStyleDeclaration, "direction" | "transition">'.
  Types of property 'x' are incompatible.
    Type 'string | number' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.

1203 interface CSSStyleDeclarationWithTransform extends Omit<CSSStyleDeclaration, "direction" | "transition"> {
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

### Step-by-step reproduction instructions

1. Remove your node modules folder `rm -r node_modules`
3. Reinstall the packages `npm install`
4. Try to build the project `npm run dev`
5. You will receive an error like the above.

### Environment info

- Gutenberg trunk
- Node 20.16
- Ubuntu 22.04

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by matiasbenedetto** [comment]
A potential fix for this: https://github.com/WordPress/gutenberg/pull/64003

**Comment by mirka** [comment]
Does `npm run clean:package-types` help?

**Comment by matiasbenedetto** [comment]
> Does npm run clean:package-types help?

Nope it's not working on my end, I tried that several times.

**Comment by t-hamano** [comment]
I cannot reproduce this problem in my environment. I can build correctly on both Node 20.15.1 and 20.16.0 🤔

**Comment by getdave** [comment]
Justing noting I was able to reproduce this today.

**Comment by manzoorwanijk** [comment]
This no longer seems to be an issue.

**Comment by matiasbenedetto** [comment]
I can no longer reproduce this, so I'm closing the issue
