### ISSUE TITLE
Bug: @wordpress/create-block Generates Nested src Directory and Fails Build Due to Missing AJV Dependencies

### ISSUE THREAD

**Issue by biplobghatak** [WordPress/gutenberg#69976]
### Description

After creating a new block using @wordpress/create-block@latest, two issues were encountered:

1. Unnecessary Nested Folder in src 
```
src/my-plugin/index.js
``` 
Expected Structure:

```
src/index.js
src/editor.scss
src/style.scss
```
This structure adds unnecessary depth, especially for single-block plugins, and can be a bit confusing. It would be more developer-friendly if the generated files were placed directly inside the src/ directory.

2. Build Fails with ajv Dependency Error

Running npm run start after plugin generation fails with the following error:

`[webpack-cli] Error: Cannot find module 'ajv/dist/compile/codegen'
`
Temporary Fix: Manually installing the dependencies resolves the issue:
`npm install ajv@8 ajv-formats ajv-keywords
`

### Step-by-step reproduction instructions

1. Run npx @wordpress/create-block my-plugin
2. Navigate into the folder (`cd my-plugin`)
3. Run npm install
4. Run npm run start

### Screenshots, screen recording, code snippet

Issue 1 : https://prnt.sc/eITqIaD9UFro

Issue 2: https://prnt.sc/pMgyTQ6zxqk8

### Environment info

- Wordpress Version : 6.8
-  Node js : 22.11.0
-  npm - 11.0.0
- OS : Windows 11
- Browser : Chrome, Brave

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by yogeshbhutkar** [comment]
Thanks for raising the issue!

> This structure adds unnecessary depth, especially for single-block plugins, and can be a bit confusing. It would be more developer-friendly if the generated files were placed directly inside the src/ directory.

This change was introduced in https://github.com/WordPress/gutenberg/pull/68175. I agree with the change made in the PR. It eases the overall process of scaffolding multiple blocks. Considering most plugins eventually implement multiple blocks, I agree with making them the default.

However, having just a single block within the plugin might be a valid use case where nesting the block files within `src/slug` might not be required. I'm aware of the [developments](https://github.com/WordPress/gutenberg/pull/67886) that occurred around a `multi variant`, I was wondering if we could have a single variant instead for covering this use case.

cc: @gziolo 

Edit:

> Build Fails with ajv Dependency Error

I tested with the latest `create-block` package, but I didn't get any build failures. I'll wait for other contributors to test it and see if it's replicable at their end.

**Comment by himanshupathak95** [comment]
I agree that the single block case can be handled differently to avoid unnecessary nesting. While the multi-block structure makes sense as a default for most plugins that will eventually contain multiple blocks, having a single variant option would improve developer experience for simpler plugins.

> I tested with the latest create-block package, but I didn't get any build failures. I'll wait for other contributors to test it and see if it's replicable at their end.

I've also tested with the latest `@wordpress/create-block` and couldn't reproduce the build failure.
The fact that manually installing those specific AJV packages fixed it suggests there's some environment-specific dependency resolution issue rather than a problem with @wordpress/create-block itself, I think.

**Comment by gziolo** [comment]
> This change was introduced in https://github.com/WordPress/gutenberg/pull/68175. I agree with the change made in the PR. It eases the overall process of scaffolding multiple blocks. Considering most plugins eventually implement multiple blocks, I agree with making them the default.

Yes, it simplifies the handling when the plugin author opts to support more than one block. In that case, the scaffolded plugin has also logic in place that optimizes block metadata reading by incorporating the block manifest file, which improves the performance. More in [More efficient block type registration in 6.8](https://make.wordpress.org/core/2025/03/13/more-efficient-block-type-registration-in-6-8/). It's a tradeoff that, depending on the use case, can be helpful or go against the vision of the developer. It's worth mentioning that the block collection functionality assumes that every block is located in its folder.

**Comment by t-hamano** [comment]
> 2. Build Fails with ajv Dependency Error
> Running npm run start after plugin generation fails with the following error:

This problem has also been reported here: https://github.com/WordPress/gutenberg/issues/62801

**Comment by youknowriad** [comment]
The src/<block-name>/ structure is intentional, it's the multi-block default introduced in [#68175](https://github.com/WordPress/gutenberg/issues/68175), which most plugins grow into (see @gziolo's comment). Closing as working as intended on that half; if the AJV missing-dependency build failure is tracked separately.
