### PR TITLE
Update Node.js requirement in create-block docs.

### PR DESCRIPTION
**Pull request by kovshenin**
## What?

Updates minimum required Node.js version from 14.0.0 to 16.9.0:

## Why?

The build currently fails with:

```
[webpack-cli] TypeError: Object.hasOwn is not a function
    at getBlockJsonScriptFields (.../node_modules/@wordpress/scripts/utils/block-json.js:28:15)
    at .../node_modules/@wordpress/scripts/utils/config.js:253:9
```

Object.hasOwn [was introduced](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility) in Node.js 16.9.0.

### CODE REVIEW

**Comment by carolinan** [comment]
Hi

I believe the npm version also needs to be increased, according to this table?
https://nodejs.org/en/about/previous-releases

The create-block/package.json file needs updating as well, it still says node version 14 or above:

```
	"engines": {
		"node": ">=14",
		"npm": ">=6.14.4"
	},
```

**Comment by gziolo** [comment]
Good point about `engines`, @carolinan. This is what Gutenberg uses:

https://github.com/WordPress/gutenberg/blob/3d9bdeebb681f2150b7718e92260f3690907e61c/package.json#L17-L20

It probably reflects actively supported Node.js versions: https://nodejs.org/en/about/previous-releases.

Maybe we should also support Node 18 which is in maintenance mode until April 2025.

**Comment by kovshenin** [comment]
Set to 18/10.5 in 415a6ed92ffcf70f1b03698d16e29d6aedefa49f given that 16 is no longer supported, though I should note that create-block worked fine with 16.9/8.19.

**Review by gziolo — APPROVED** [review]
Nice, thank you so much for this patch.

I think we should add a changelog entry with the breaking changes section just for the sake of documentation purposes like in:
https://github.com/WordPress/gutenberg/blob/trunk/packages/create-block/CHANGELOG.md#breaking-change

I don't think `@wordpress/create-block` is used as a regular dependency in projects, but technically speaking it is a breaking change.

**Comment by gziolo** [comment]
I think you still need to run `npm i` so the lock file updates with the engine changes.

**Comment by Mamaduka** [comment]
I'm going to merge this. The Windows job failure is a [known issue](https://wordpress.slack.com/archives/C02QB2JS7/p1714705796265889) (a Slack link requires login).

**Comment by afercia** [comment]
Couple questions: really not my area of expertise but:
- Why the npm version has been increased to `>=10.5.0` only in the `create-block` package.json and not in the main package.json?
- Shouldn't node/npm version changes be coordinated with Core? 

For me, I was already on `node 20.10.0` and `npm 10.2.3`. I guess that is what people who are contributing since a while have. I had to update only to get the new `npm` version. [Core still requires](https://github.com/WordPress/wordpress-develop/blob/b0308b8f5299362c8a12e45e83d6a26cb01d7325/package.json#L9-L12) npm greater or equal to 10.2.3.
Cc @desrosj

**Comment by gziolo** [comment]
I missed the `npm` version being higher than `10.2.3`. It definitely should align with what Gutenberg and WP core use.

In fact, for npm packages we should define 20.9.0 as the minimum required Node.js version based on the fact that it was the first LTS version: https://nodejs.org/en/blog/release/v20.9.0.

Node `v20.9.0` comes with npm `v10.1.0` so that should also be a minimum version used.

**Comment by afercia** [comment]
Thx for double checking @gziolo.
Are you on a follow-up for GB and Core?

**Comment by Mamaduka** [comment]
I created a follow-up PR - #60962. Let's keep Gutneberg and Core versions in sync.
