### PR TITLE
DatePicker: Fix crash when navigating between months

### PR DESCRIPTION
**Pull request by mirka**
## Description

A bug was introduced in #29716 that causes a `onMonthPreviewed is not a function` crash when the prev/next month buttons are clicked in `DatePicker` (but not `DateTimePicker`).

This PR:

- Adds a `DatePicker` story in Storybook for testing.
- Fixes the component so it doesn't call the `onMonthPreviewed` prop function if it wasn't passed.

## How has this been tested?

Both the `DatePicker` and `DateTimePicker` components in Storybook work as expected.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
I was able to replicate the bug using the storybook without the non-storybook change, and confirmed the change fixes the issue.
