### PR TITLE
Build: Preserve `__esModule` on `window.wp.*` IIFE globals for webpack interop

### LINKED ISSUE #78697: esbuild build pipeline strips `__esModule` from `window.wp.*` globals, breaking webpack default-import interop for external consumers
## What I expected

External plugins (e.g. WooCommerce) that consume `@wordpress/*` packages as webpack externals can use default imports against the `window.wp.*` globals:

```ts
import isShallowEqual from '@wordpress/is-shallow-equal';
isShallowEqual( a, b );
```

This worked in the webpack-based bundle pipeline because the IIFE preserved `Object.defineProperty( ns, '__esModule', { value: true } )`, and webpack's `__webpack_require__.n( wp.isShallowEqual )` then returned `() => wp.isShallowEqual.default`.

## What actually happens

PR #72140 / packages/wp-build/lib/build.mjs appends a footer to every `window.wp.*` IIFE:

```js
// packages/wp-build/lib/build.mjs (around line 580)
if ( globalName ) {
    footerParts.push(
        `if(${globalName}&&typeof ${globalName}==='object'){${globalName}=Object.assign({},${globalName});}`
    );
}
```

So the built bundle now ends with, for example:

```js
if ( wp.isShallowEqual && typeof wp.isShallowEqual === 'object' ) {
    wp.isShallowEqual = Object.assign( {}, wp.isShallowEqual );
}
```

`__esModule` is declared via `Object.defineProperty( ns, '__esModule', { value: true } )` (non-enumerable by default). `Object.assign( {}, source )` only copies enumerable own properties, so the new object loses `__esModule`.

Once `__esModule` is gone, webpack's runtime interop helper (`__webpack_require__.n`) takes the CommonJS branch and returns `() => module` (the whole namespace) instead of `() => module.default`. Any external consumer doing `import X from '@wordpress/<package>'` then ends up calling the namespace object as a function:

```
TypeError: isShallowEqual is not a function
```

## Repro

1. Run a recent Gutenberg trunk build locally (or grab the [bph/gutenberg](https://github.com/bph/gutenberg) nightly).
2. In a separate plugin that uses `@wordpress/is-shallow-equal` (or any other affected package) as a webpack external:
   ```ts
   import isShallowEqual from '@wordpress/is-shallow-equal';
   console.log( isShallowEqual( { a: 1 }, { a: 1 } ) );
   ```
3. Boot the plugin in a WP install that has Gutenberg trunk active; the call throws `TypeError`.

I hit this in WooCommerce — Gutenberg trunk crashes the Cart block via [`client/blocks/assets/js/data/cart/push-changes.ts:197`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/data/cart/push-changes.ts#L197), which calls `isShallowEqual( localState.customerData, … )`. Pageerror in DevTools:

```
TypeError: vr(...) is not a function
    at wc-blocks-data.js:5:17588
    at gutenberg/build/scripts/data/index.min.js
    at Object.dispatch
```

`vr` is webpack's `__webpack_require__.n` helper.

Verified the same footer is appended to every WP-script bundle:

```
=== is-shallow-equal ===  wp.isShallowEqual=Object.assign({},wp.isShallowEqual)
=== data ===              wp.data=Object.assign({},wp.data)
=== data-controls ===     wp.dataControls=Object.assign({},wp.dataControls)
=== api-fetch ===         wp.apiFetch=Object.assign({},wp.apiFetch)
=== element ===           wp.element=Object.assign({},wp.element)
=== compose ===           wp.compose=Object.assign({},wp.compose)
=== hooks ===             wp.hooks=Object.assign({},wp.hooks)
=== notices ===           wp.notices=Object.assign({},wp.notices)
```

Packages with `wpScriptDefaultExport: true` (like `api-fetch`) are unwrapped to a function first and skip the second footer (`typeof !== 'object'`), so they're not affected — but every package with `wpScriptDefaultExport` falsy/missing **that still has a default export** is.

I noticed `packages/is-shallow-equal/src/index.ts` already has this comment:

```ts
// `isShallowEqual` is exported also as a named export because esbuild cannot
// expose the default export from the `window.wp.isShallowEqual` global.
export { isShallowEqual, isShallowEqualObjects, isShallowEqualArrays };
```

…so the team is aware default imports don't work and is migrating consumers to named imports. The issue is that external consumers (WooCommerce, third-party plugins) don't have a clean migration path:

- The npm package `@wordpress/is-shallow-equal@4.58.0` still only exports `default`, so `import { isShallowEqual } from '@wordpress/is-shallow-equal'` doesn't type-check.
- The runtime behavior differs between WordPress core's bundled build (`__esModule` preserved — default imports work) and Gutenberg trunk (`__esModule` stripped — default imports break). Consumers need to pick one or compose a per-package shim.

## Suggested fixes

Any of the following in `packages/wp-build/lib/build.mjs` would preserve interop transparently:

```js
// Option A — re-declare __esModule non-enumerable on the copy:
if ( globalName ) {
    footerParts.push(
        `if(${globalName}&&typeof ${globalName}==='object'){` +
            `var __c=Object.assign({},${globalName});` +
            `if(${globalName}.__esModule)Object.defineProperty(__c,'__esModule',{value:true});` +
            `${globalName}=__c;` +
        `}`
    );
}

// Option B — skip the materialization when the module is an ESM namespace:
if ( globalName ) {
    footerParts.push(
        `if(${globalName}&&typeof ${globalName}==='object'&&!${globalName}.__esModule){` +
            `${globalName}=Object.assign({},${globalName});` +
        `}`
    );
}

// Option C — copy non-enumerable descriptors too:
if ( globalName ) {
    footerParts.push(
        `if(${globalName}&&typeof ${globalName}==='object'){` +
            `${globalName}=Object.defineProperties({},Object.getOwnPropertyDescriptors(${globalName}));` +
        `}`
    );
}
```

Option C preserves *all* non-enumerable descriptors (including `__esModule` and anything else the esbuild output uses internally), at slightly higher cost than `Object.assign`.

## Impact

Anything outside Gutenberg that uses a `@wordpress/*` package as a webpack external and imports a default export. Off the top of my head: WooCommerce (Cart/Checkout blocks crash on trunk), almost certainly other large plugins, and probably the WordPress.com / WP-Admin Calypso bundles.

## Environment

- Gutenberg 23.3.20260523 (nightly via bph/gutenberg)
- WordPress 6.x test container (wp-env)
- Webpack-based consumer

### PR DESCRIPTION
**Pull request by kraftbj**
## What?

Closes #78697

The esbuild build pipeline introduced in #72140 appends a footer to every `window.wp.*` IIFE bundle that materializes esbuild's getter-based exports as data properties via `Object.assign( {}, ns )`. The shallow copy drops esbuild's non-enumerable `__esModule: true` marker, which broke webpack default-import interop for external consumers (e.g. WooCommerce — Cart/Checkout blocks crash against Gutenberg trunk because `isShallowEqual` resolves to the whole namespace object instead of the default function).

## Why?

`Object.assign( {}, source )` only copies enumerable own properties. esbuild's `__toCommonJS` helper declares `__esModule` via `Object.defineProperty( ns, '__esModule', { value: true } )`, which is non-enumerable by default, so the marker was lost on the rebuilt namespace.

Once `__esModule` is gone, webpack's `__webpack_require__.n( wp.foo )` interop helper takes the CommonJS branch and returns `() => wp.foo` (the whole namespace) instead of `() => wp.foo.default`. Consumers doing `import isShallowEqual from 'wordpress/is-shallow-equal'` then call the namespace as a function and crash:

\`\`\`
TypeError: isShallowEqual is not a function
\`\`\`

Every Gutenberg package with a default export and `wpScript` enabled was affected. The original webpack pipeline preserved the marker via the IIFE's internal `Object.defineProperty(…, '__esModule')`, so the bundled WordPress core build still works — only Gutenberg trunk (and the nightly build) regress.

## How?

The second footer (the one that materializes getters) now branches on `wpScriptDefaultExport`:

- **Non-default-export packages** (`wpScriptDefaultExport` is falsy): the global is the ES module namespace. Re-seed the `Object.assign` target with a non-enumerable, writable `__esModule` when the source has it. The perf optimization (getters → data properties, ~2x cheaper per access in V8) is preserved because the enumerable getters still flow through `Object.assign`. The target's `__esModule` is marked writable so a hypothetical future esbuild emit that makes the source's `__esModule` enumerable would not trip a strict-mode `TypeError` when `Object.assign` walks it.
- **`wpScriptDefaultExport` packages**: the first footer has already unwrapped the global to its default value (today always a function or class for the eight current opt-ins: `api-fetch`, `deprecated`, `dom-ready`, `redux-routine`, `server-side-render`, `warning`, `token-list`, `shortcode`). Keep the plain `Object.assign( {}, ns )` to materialize any getters; this also drops any stray `__esModule` flag the unwrapped default might carry, which is correct — the global no longer represents an ES module namespace, so webpack's interop should take the CJS branch and return the value directly. (For function/class defaults the second footer is a no-op anyway because `typeof !== 'object'`, so no observable change for current packages.)

The new comment block documents both branches.

## Testing Instructions

1. Build any package (e.g. `npm run build:packages`) and inspect the IIFE footer for one of the affected globals:
   \`\`\`
   tail -c 200 build/is-shallow-equal/index.min.js
   \`\`\`
   The footer now reads (roughly):
   \`\`\`
   if(wp.isShallowEqual&&typeof wp.isShallowEqual==='object'){wp.isShallowEqual=Object.assign(wp.isShallowEqual.__esModule?Object.defineProperty({},'__esModule',{value:true,writable:true}):{},wp.isShallowEqual);}
   \`\`\`
2. Load the bundle in a browser:
   \`\`\`js
   wp.isShallowEqual.__esModule          // true
   Object.keys( wp.isShallowEqual )      // does not include '__esModule'
   typeof wp.isShallowEqual.default      // 'function'
   \`\`\`
3. End-to-end repro: boot the [bph/gutenberg](https://github.com/bph/gutenberg) nightly setup (or build trunk locally) with WooCommerce installed, then visit a page with the Cart block. Before this PR the page errors with `TypeError: vr(...) is not a function` (webpack's `__webpack_require__.n` helper) from `wc-blocks-data.js`. After this PR the Cart block renders.
4. Confirm the eight `wpScriptDefaultExport` packages still expose their default value as the global (`typeof wp.apiFetch === 'function'`, `new wp.shortcode( … )`, etc.).

### Testing Instructions for Keyboard

Not applicable — build-tool change with no UI surface.

## Screenshots or screencast

Not applicable.

## Use of AI Tools

Yes — Claude Code was used to draft the fix from the analysis in the linked issue and to run iterative adversarial reviews (multiple passes of compound-engineering and Codex CLI). I verified each step, wrote the test scenarios, and reviewed every line.

### CODE REVIEW

**Review by prettyboymp — APPROVED** [review]
I tested against WooCommerce core and this fixed the issue with the conversion of `is-shallow-equal` that was introduced.

**Comment by arthur791004** [comment]
Let's loop in @youknowriad for feedback, since this is related to #72140 as mentioned 🙂

**Comment by youknowriad** [comment]
Thanks for the fix, trying to understand a bit better. esbuild switch happened on the previous WP release, is this a new issue? Why is it only surfacing now on Woo?

**Comment by jsnajdr** [comment]
The cause of this bug is a very recent optimization by @ellatrix in #78303. One of the optimizations we did during our RSM projects 🙂 

The `is-shallow-equal` package should be the only one affected, because it's the only one that has a default export and named exports, too. Other packages are either "one default export only" or "multiple named exports and no default". The `__esModule` field is not crucial for them.

File: packages/wp-build/lib/build.mjs [hunk 1]
```diff
@@ -587,9 +587,35 @@ async function bundlePackage( packageName, options = {} ) {
 			// esbuild marks the getters non-configurable, so we can't rewrite
 			// them in place; replacing the whole namespace with a shallow
 			// copy is the simplest way to materialize each value once.
-			footerParts.push(
-				`if(${ globalName }&&typeof ${ globalName }==='object'){${ globalName }=Object.assign({},${ globalName });}`
-			);
```
Comment (jsnajdr) [inline packages/wp-build/lib/build.mjs:592]: I think that all we need to do is that instead of `Object.assign({}, ...)` we do `Object.assign({ __esModule: true }, ...)`. That covers everything, the patch doesn't need to be that complicated.

Comment (kraftbj) [reply packages/wp-build/lib/build.mjs:592]: Good call, that's much cleaner — pre-seeding the target also makes the `writable` concern moot in the common case. One tweak: a plain `{ __esModule: true }` literal defines the property as enumerable, but esbuild's `__toCommonJS` (and webpack's own `__webpack_require__.r`) mark it non-enumerable, so the literal would leak `__esModule` into `Object.keys()`, spread, and downstream `Object.assign`. Keeping it non-enumerable is still a one-liner:

```js
`if(${ globalName }&&typeof ${ globalName }==='object'){${ globalName }=Object.assign(Object.defineProperty({},'__esModule',{value:true,writable:true}),${ globalName });}`
```

That drops both the conditional and the two-branch split. I kept `writable: true` as a cheap guard so a future esbuild change emitting an enumerable `__esModule` wouldn't trip a strict-mode write when `Object.assign` copies it — happy to drop it if you'd rather keep it minimal. Pushed in be32a3d.

**Review by gigitux — APPROVED** [review]
Let's wait for @jsnajdr for the last feedback, but I tested this patch with WooCommerce and I'm unable to reproduce the issue. I wonder if it makes sense to add a unit test to cover this use-case. I added it in https://github.com/WordPress/gutenberg/pull/78911

File: packages/wp-build/lib/build.mjs (hunk 1 above)
Comment (jsnajdr) [reply packages/wp-build/lib/build.mjs:592]: Yes, it's great that `Object.defineProperty` returns the object 🙂

File: packages/wp-build/lib/build.mjs [hunk 2]
```diff
@@ -585,10 +585,22 @@ async function bundlePackage( packageName, options = {} ) {
...
+			// `__webpack_require__.n` helper in external consumers (e.g.
+			// WooCommerce) still resolves `import X from '@wordpress/<package>'`
+			// to `.default` rather than the whole namespace. A plain
+			// `Object.assign({}, …)` would otherwise drop esbuild's
+			// non-enumerable `__esModule` marker. Non-enumerable matches the
+			// descriptor esbuild's `__toCommonJS` (and webpack's own
+			// `__webpack_require__.r`) emit, so it does not leak into
+			// `Object.keys`, spread, or downstream `Object.assign`. `writable`
+			// guards against a strict-mode write if a future esbuild ever
+			// emitted an enumerable `__esModule` for `Object.assign` to copy.
```
Comment (jsnajdr) [inline packages/wp-build/lib/build.mjs]: This comment is too long and includes too many internal details about bundlers. I would write it as:

> Seed the copy with a non-enumerable `__esModule` flag so that bundlers treat it as an ESM module, triggering interop conventions for default exports.

**Review by jsnajdr — APPROVED** [review]
Looks good :+1:

File: packages/wp-build/lib/build.mjs (hunk 2 above)
Comment (kraftbj) [reply packages/wp-build/lib/build.mjs]: Done in cbca833 — used your wording, kept the existing line about materializing the getters.

**Comment by kraftbj** [comment]
Superceded by #78917

**Comment by aduth** [comment]
Is it superseded? My impression is that #78917 was a temporary fix, but also regresses the performance gains from #78303, and that the changes you were proposing here would maintain the performance improvements without the breakage.

In other words, I think this is still good to try to land, no?

**Comment by jsnajdr** [comment]
@gigitux reported in a private convo that this `__esModule` fix didn't work for him. Referring to my suggestion in https://github.com/WordPress/gutenberg/pull/78911#issuecomment-4613024651:

> @jsnajdr I tried your suggestion, but I got the same issue

> In other words, I think this is still good to try to land, no?

I'm not 100% sure if the right patch has exactly the form as in this PR, but yes, it's time to try the optimization again, this time not breaking the ESM interop.

**Comment by kraftbj** [comment]
Yeah, I closed it in the sense that whenever 78303 is retried, the acceptance criteria would need to include not breaking what it broke previously. Thus, this as a standalone PR would be superseded (even if it is otherwise correct).
